TAB_MAPPING = {  
    ["0"] = {"Overworld"},
    ["40"] = {"Overworld"}, -- Fairy House
    ["41"] = {"Combos"}, -- Kadishu Card Shop
    ["42"] = {"Combos"}, -- Grenfoel Cathedral Shop
    ["1"] = {"Bhashea", "Nobleman's Residence"},
    ["2"] = {"Bhashea", "Bhashea High Road"},
    ["3"] = {"Bhashea", "Kadishu"},
    ["22"] = {"Bhashea", "Gromtull Desert"},
    ["4"] = {"Bhashea", "Kendarie Fortress"},
    ["21"] = {"Bhashea", "Bhashea Castle"},
    ["20"] = {"Bhashea", "Isamat Urbur"},
    ["5"] = {"Kendaria", "Runestone Caverns - Upper Chambers"},
    ["6"] = {"Kendaria", "Runestone Caverns - Lower Chambers"},
    ["7"] = {"Kendaria", "Ruldo Forest"},
    ["17"] = {"Kendaria", "Fossil Boneyard"},
    ["8"] = {"Kendaria", "Sarvan"},
    ["23"] = {"Kendaria", "Sacred Battle Arena 1"},
    ["24"] = {"Kendaria", "Sacred Battle Arena 2"},
    ["9"] = {"Alanjeh", "Holzogh Town"},
    ["10"] = {"Alanjeh", "Plains of Rowahl"},
    ["11"] = {"Alanjeh", "Alanjeh Castle"},
    ["12"] = {"Alanjeh", "Royal Tower - Lower"}, -- First visit
    ["18"] = {"Alanjeh", "Royal Tower - Lower"},
    ["15"] = {"Alanjeh", "Royal Tower - Middle"},
    ["16"] = {"Alanjeh", "Royal Tower - Upper"},
    ["25"] = {"Alanjeh", "Obenoix Gorge"},
    ["13"] = {"Wyht", "Krasheen Mountains"},
    ["14"] = {"Wyht", "Grenfoel Cathedral"},
    ["27"] = {"Wyht", "Temple of Sharacia"},
    ["50"] = {"Wyht", "Proving Grounds"}, -- 1F
    ["51"] = {"Wyht", "Proving Grounds"}, -- 2F
    ["52"] = {"Wyht", "Proving Grounds"}, -- 3F
    ["53"] = {"Wyht", "Proving Grounds"}, -- 4F
    ["54"] = {"Wyht", "Proving Grounds"}, -- 5F
    ["55"] = {"Wyht", "Proving Grounds"}, -- 6F
    ["56"] = {"Wyht", "Proving Grounds"}, -- 7F
    ["57"] = {"Wyht", "Proving Grounds"}, -- 8F
    ["58"] = {"Wyht", "Proving Grounds"}, -- 9F
    ["59"] = {"Wyht", "Proving Grounds"}, -- 10F
    ["60"] = {"Wyht", "Proving Grounds"}, -- 11F
    ["61"] = {"Wyht", "Proving Grounds"}, -- 12F
    ["62"] = {"Wyht", "Proving Grounds"}, -- 13F
    ["63"] = {"Wyht", "Proving Grounds"}, -- 14F
    ["64"] = {"Wyht", "Proving Grounds"}, -- 15F
    ["65"] = {"Wyht", "Proving Grounds"}, -- 16F
    ["66"] = {"Wyht", "Proving Grounds"}, -- 17F
    ["67"] = {"Wyht", "Proving Grounds"}, -- 18F
    ["68"] = {"Wyht", "Proving Grounds"}, -- 19F
    ["69"] = {"Wyht", "Proving Grounds"}, -- 20F
}