Tracker:AddLocations("locations/Alanjeh Castle.json")
Tracker:AddLocations("locations/Bhashea Castle.json")
Tracker:AddLocations("locations/Bhashea High Road.json")
Tracker:AddLocations("locations/Combo.json")
Tracker:AddLocations("locations/Fairy House.json")
Tracker:AddLocations("locations/Fossil Boneyard.json")
Tracker:AddLocations("locations/Grenfoel Cathedral.json")
Tracker:AddLocations("locations/Grenfoel Church.json")
Tracker:AddLocations("locations/Gromtull Desert.json")
Tracker:AddLocations("locations/Holzogh Town.json")
Tracker:AddLocations("locations/Isamat Urbur.json")
Tracker:AddLocations("locations/Kadishu.json")
Tracker:AddLocations("locations/Kendarie Fortress.json")
Tracker:AddLocations("locations/Krasheen Mountains.json")
Tracker:AddLocations("locations/Noblemans Residence.json")
Tracker:AddLocations("locations/Obenoix Gorge.json")
Tracker:AddLocations("locations/Plains of Rowahl.json")
Tracker:AddLocations("locations/Royal Tower - Lower.json")
Tracker:AddLocations("locations/Royal Tower - Middle.json")
Tracker:AddLocations("locations/Royal Tower - Upper.json")
Tracker:AddLocations("locations/Ruldo Forest.json")
Tracker:AddLocations("locations/Runestone Caverns - Lower Chambers.json")
Tracker:AddLocations("locations/Runestone Caverns - Upper Chambers.json")
Tracker:AddLocations("locations/Sacred Battle Arena 1.json")
Tracker:AddLocations("locations/Sacred Battle Arena 2.json")
Tracker:AddLocations("locations/Sarvan.json")
Tracker:AddLocations("locations/Temple of Sharacia.json")
Tracker:AddLocations("locations/Overworld.json")
